fail_fast: true
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args:
        - --profile=black
        - --filter-files
        - --line-length=79
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --line-length=79
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --extend-ignore=E203
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
